<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Installation;

use LogicException;

final readonly class InstallationComposeRenderer
{
    public function __construct(private InstallationServiceCatalog $catalog = new InstallationServiceCatalog) {}

    public function render(InstallationSelection $selection): string
    {
        if ($selection->provider !== 'compose') {
            throw new LogicException('A Compose file can only be rendered for the Compose provider.');
        }

        $blocks = [];
        $volumes = [];

        foreach ($selection->services() as $service) {
            // Fail early if catalog metadata and rendering ever drift apart.
            $this->catalog->portsFor($service);
            $blocks[] = $this->service($service);
            if ($this->usesVolume($service)) {
                $volumes[] = "  {$service}-data:";
            }
        }

        $yaml = "# Generated by Harbour. PHP and Node continue to run natively.\nservices:\n"
            .implode("\n", $blocks);

        if ($volumes !== []) {
            $yaml .= "\nvolumes:\n".implode("\n", $volumes)."\n";
        }

        return $yaml;
    }

    private function service(string $service): string
    {
        return match ($service) {
            'mysql' => <<<'YAML'
  mysql:
    image: mysql:8.4
    ports:
      - "127.0.0.1:${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: harbour
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "0"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pharbour"]
      retries: 10
      timeout: 5s
YAML,
            'pgsql' => <<<'YAML'
  pgsql:
    image: postgres:18-alpine
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: harbour
      POSTGRES_PASSWORD: harbour
    volumes:
      - pgsql-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "harbour"]
      retries: 10
      timeout: 5s
YAML,
            'mariadb' => <<<'YAML'
  mariadb:
    image: mariadb:11
    ports:
      - "127.0.0.1:${DB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: harbour
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      retries: 10
      timeout: 5s
YAML,
            'mongodb' => <<<'YAML'
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - "127.0.0.1:${MONGODB_PORT}:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://localhost:27017/admin", "--quiet", "--eval=db.runCommand({ping:1})"]
      retries: 10
      timeout: 5s
YAML,
            'redis' => <<<'YAML'
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 10
      timeout: 5s
YAML,
            'valkey' => <<<'YAML'
  valkey:
    image: valkey/valkey:alpine
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      retries: 10
      timeout: 5s
YAML,
            'memcached' => <<<'YAML'
  memcached:
    image: memcached:alpine
    ports:
      - "127.0.0.1:${MEMCACHED_PORT}:11211"
YAML,
            'meilisearch' => <<<'YAML'
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "127.0.0.1:${MEILISEARCH_PORT}:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://127.0.0.1:7700/health"]
      retries: 10
      timeout: 5s
YAML,
            'typesense' => <<<'YAML'
  typesense:
    image: typesense/typesense:27.1
    ports:
      - "127.0.0.1:${TYPESENSE_PORT}:8108"
    environment:
      TYPESENSE_DATA_DIR: /typesense-data
      TYPESENSE_API_KEY: xyz
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - typesense-data:/typesense-data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://127.0.0.1:8108/health"]
      retries: 10
      timeout: 5s
YAML,
            'minio' => <<<'YAML'
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":8900"
    ports:
      - "127.0.0.1:${MINIO_PORT}:9000"
      - "127.0.0.1:${MINIO_CONSOLE_PORT}:8900"
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      retries: 10
      timeout: 5s
YAML,
            'rustfs' => <<<'YAML'
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "127.0.0.1:${RUSTFS_PORT}:9000"
      - "127.0.0.1:${RUSTFS_CONSOLE_PORT}:9001"
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
    volumes:
      - rustfs-data:/data
YAML,
            'mailpit' => <<<'YAML'
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "127.0.0.1:${MAIL_PORT}:1025"
      - "127.0.0.1:${MAILPIT_DASHBOARD_PORT}:8025"
YAML,
            'rabbitmq' => <<<'YAML'
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "127.0.0.1:${RABBITMQ_PORT}:5672"
      - "127.0.0.1:${RABBITMQ_DASHBOARD_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: harbour
      RABBITMQ_DEFAULT_PASS: harbour
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      retries: 10
      timeout: 5s
YAML,
            'selenium' => <<<'YAML'
  selenium:
    image: selenium/standalone-chromium
    ports:
      - "127.0.0.1:${SELENIUM_PORT}:4444"
    shm_size: 2gb
YAML,
            'soketi' => <<<'YAML'
  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    ports:
      - "127.0.0.1:${PUSHER_PORT}:6001"
      - "127.0.0.1:${PUSHER_METRICS_PORT}:9601"
    environment:
      SOKETI_DEFAULT_APP_ID: app-id
      SOKETI_DEFAULT_APP_KEY: app-key
      SOKETI_DEFAULT_APP_SECRET: app-secret
      SOKETI_METRICS_SERVER_PORT: "9601"
YAML,
            default => throw new LogicException("Unsupported Compose service [{$service}]."),
        };
    }

    private function usesVolume(string $service): bool
    {
        return in_array($service, [
            'mysql', 'pgsql', 'mariadb', 'mongodb', 'redis', 'valkey',
            'meilisearch', 'typesense', 'minio', 'rustfs', 'rabbitmq',
        ], true);
    }
}
