<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Installation;

final class InstallationFileRenderer
{
    public function __construct(private readonly InstallationServiceCatalog $services = new InstallationServiceCatalog) {}

    public function environment(InstallationSelection|InstallationDiscovery $installation): string
    {
        $discovery = $this->discovery($installation);
        $selection = $discovery->selection;
        $sections = [
            $this->baseEnvironment($discovery),
            $this->databaseEnvironment($selection->database, $discovery),
            $this->cacheEnvironment($selection->cache, $discovery),
            $this->mailEnvironment($selection->mail, $discovery),
        ];

        foreach ($selection->additionalServices as $service) {
            $sections[] = $this->serviceEnvironment($service, $discovery);
        }

        $variables = [];
        foreach ($sections as $section) {
            foreach (preg_split('/\R/', $section) ?: [] as $line) {
                if ($line === '') {
                    continue;
                }
                $separator = strpos($line, '=');
                if ($separator !== false) {
                    $variables[substr($line, 0, $separator)] = $line;
                }
            }
        }

        return "# Generated by Harbour. Re-run workspace:install --reconfigure to update.\n".implode("\n", $variables)."\n";
    }

    public function configuration(InstallationSelection|InstallationDiscovery $installation): string
    {
        $discovery = $this->discovery($installation);
        $selection = $discovery->selection;
        $databaseEnabled = $selection->database === 'sqlite'
            || (in_array($selection->database, $this->services->namesFor('database'), true)
                && $this->services->get($selection->database)->ownsSqlLifecycle);
        $databaseConnection = $databaseEnabled ? $selection->database : null;
        $installation = $this->export([...$selection->toArray(), 'discovery' => $discovery->metadata()], 1);
        $services = [];
        if ($selection->provider === 'shared') {
            foreach ($selection->services() as $service) {
                $services[$service] = ['driver' => 'shared'];
            }
        }
        $exportedServices = $this->export($services, 1);
        $compose = $selection->provider === 'compose'
            ? ['services' => [
                'file' => 'docker-compose.harbour.yml',
                'ports' => $this->services->portDefinitions($selection->services()),
            ]]
            : [];
        $exportedCompose = $this->export($compose, 1);
        $enabled = $databaseEnabled ? 'true' : 'false';
        $connection = $databaseConnection === null ? 'null' : "'{$databaseConnection}'";
        $databaseComment = $selection->database === 'mongodb'
            ? "// MongoDB is connection-only: Harbour never creates, marks,\n            // migrates, or destroys the selected MongoDB database."
            : '// SQL lifecycle is guarded by the persisted Harbour ownership marker.';

        return <<<PHP
        <?php

        declare(strict_types=1);

        // Generated by Harbour. Re-run workspace:install --reconfigure to update.

        use PickeringTech\Harbour\Identity\DefaultWorkspaceIdentityStrategy;
        use PickeringTech\Harbour\Ports\DefaultPortAllocationStrategy;

        return [
            'enabled' => env('HARBOUR_ENABLED', in_array(env('APP_ENV'), ['local', 'testing'], true)),

            'template' => '.env.harbour',
            'state' => '.harbour.json',
            'project_name' => env('APP_NAME'),
            'workspace_path' => null,

            // Recorded so the selected installation is reviewable and reproducible.
            'installation' => {$installation},

            'identity' => [
                'strategy' => DefaultWorkspaceIdentityStrategy::class,
            ],

            'registry' => [
                'path' => env('HARBOUR_STATE_HOME'),
            ],

            'ports' => [
                'strategy' => DefaultPortAllocationStrategy::class,
                'allocations' => [
                    'APP_PORT' => ['range' => [8000, 8999]],
                    'VITE_PORT' => ['range' => [9000, 9999]],
                    'REVERB_PORT' => ['range' => [10000, 10999]],
                ],
            ],

            'vite' => [
                'hot_file' => env('VITE_HOT_FILE'),
            ],

            {$databaseComment}
            'database' => [
                'enabled' => {$enabled},
                'connection' => {$connection},
                'sqlite_path' => 'database/harbour.sqlite',
                'migrate' => {$enabled},
                'seed' => false,
            ],

            'variables' => [],
            'resolvers' => [],

            // Shared services are reused; Compose services are owned per workspace.
            'services' => {$exportedServices},
            'compose' => {$exportedCompose},

            'hooks' => [
                // Prefer argv lists, for example [PHP_BINARY, 'artisan', 'about'].
                // String hooks are supported and intentionally run through a shell.
                'before_setup' => [],
                'after_setup' => [],
                'before_teardown' => [],
                'after_teardown' => [],
            ],
        ];

        PHP;
    }

    private function baseEnvironment(InstallationDiscovery $discovery): string
    {
        $appName = $discovery->templateValue('APP_NAME', 'Laravel');

        $environment = <<<ENV
        APP_NAME={$appName}
        APP_ENV=local
        APP_KEY=\${APP_KEY}
        APP_DEBUG=true
        APP_URL=\${APP_URL}
        APP_PORT=\${APP_PORT}

        REDIS_PREFIX=\${REDIS_PREFIX}
        CACHE_PREFIX=\${CACHE_PREFIX}
        SESSION_COOKIE=\${SESSION_COOKIE}
        QUEUE_PREFIX=\${QUEUE_PREFIX}
        QUEUE_NAME=\${QUEUE_NAME}
        REDIS_QUEUE=\${REDIS_QUEUE}
        HORIZON_PREFIX=\${HORIZON_PREFIX}

        VITE_PORT=\${VITE_PORT}
        REVERB_HOST=127.0.0.1
        REVERB_PORT=\${REVERB_PORT}
        REVERB_SERVER_HOST=127.0.0.1
        REVERB_SERVER_PORT=\${REVERB_PORT}
        ENV;

        foreach (['REVERB_APP_ID', 'REVERB_APP_KEY', 'REVERB_APP_SECRET', 'REVERB_SCHEME'] as $variable) {
            if ($discovery->hasEnvironmentVariable($variable)) {
                $environment .= "\n".$variable.'=${'.$variable.'}';
            }
        }
        if ($discovery->hasEnvironmentVariable('BROADCAST_CONNECTION')) {
            $environment .= "\nBROADCAST_CONNECTION=\${BROADCAST_CONNECTION}";
        }
        if ($discovery->hasEnvironmentVariable('REVERB_APP_KEY')) {
            $scheme = $discovery->templateValue('REVERB_SCHEME', 'http');
            $environment .= "\nVITE_REVERB_APP_KEY=\${REVERB_APP_KEY}"
                ."\nVITE_REVERB_HOST=127.0.0.1"
                ."\nVITE_REVERB_PORT=\${REVERB_PORT}"
                ."\nVITE_REVERB_SCHEME={$scheme}";
        }

        return $environment;
    }

    private function databaseEnvironment(string $database, InstallationDiscovery $discovery): string
    {
        return match ($database) {
            'none' => "DB_CONNECTION=sqlite\nDB_DATABASE=:memory:",
            'sqlite' => "DB_CONNECTION=sqlite\nDB_DATABASE=\${DB_DATABASE}",
            default => $this->renderServiceEnvironment($database, $discovery),
        };
    }

    private function cacheEnvironment(string $cache, InstallationDiscovery $discovery): string
    {
        return match ($cache) {
            'none' => "CACHE_STORE=array\nSESSION_DRIVER=array\nQUEUE_CONNECTION=sync",
            'file' => "CACHE_STORE=file\nSESSION_DRIVER=file\nQUEUE_CONNECTION=sync",
            'database' => "CACHE_STORE=database\nSESSION_DRIVER=database\nQUEUE_CONNECTION=database",
            default => $this->renderServiceEnvironment($cache, $discovery),
        };
    }

    private function mailEnvironment(string $mail, InstallationDiscovery $discovery): string
    {
        return match ($mail) {
            'none' => 'MAIL_MAILER=array',
            'log' => 'MAIL_MAILER=log',
            default => $this->renderServiceEnvironment($mail, $discovery),
        };
    }

    private function serviceEnvironment(string $service, InstallationDiscovery $discovery): string
    {
        return $this->renderServiceEnvironment($service, $discovery);
    }

    private function renderServiceEnvironment(string $name, InstallationDiscovery $discovery): string
    {
        $service = $this->services->get($name);
        $rendered = preg_replace_callback(
            '/\{\{value:([^|}\r\n]+)\|([^\r\n]*)\}\}/',
            fn (array $match): string => $discovery->serviceValue(
                $match[1],
                $service->name,
                $this->renderPorts($match[2], $service, $discovery),
            ),
            $service->environmentFragment,
        ) ?? $service->environmentFragment;
        $rendered = $this->renderPorts($rendered, $service, $discovery);
        $rendered = preg_replace_callback(
            '/\{\{managed-template:([^|}]+)\|([^|}]*)\|([^}]*)\}\}/',
            fn (array $match): string => $discovery->selection->provider === 'compose'
                ? $match[2]
                : $discovery->templateValue($match[1], $match[3]),
            $rendered,
        ) ?? $rendered;
        $rendered = preg_replace_callback(
            '/\{\{template:([^|}]+)\|([^}]*)\}\}/',
            fn (array $match): string => $discovery->templateValue($match[1], $match[2]),
            $rendered,
        ) ?? $rendered;
        $rendered = preg_replace_callback(
            '/\{\{host:([^}]+)\}\}/',
            fn (array $match): string => $discovery->serviceHost($match[1], $service->name),
            $rendered,
        ) ?? $rendered;

        return $rendered;
    }

    private function export(mixed $value, int $depth): string
    {
        if (! is_array($value)) {
            return var_export($value, true);
        }
        if ($value === []) {
            return '[]';
        }

        $list = array_is_list($value);
        $lines = ['['];
        foreach ($value as $key => $item) {
            $prefix = $list ? '' : var_export($key, true).' => ';
            $lines[] = str_repeat('    ', $depth + 1).$prefix.$this->export($item, $depth + 1).',';
        }
        $lines[] = str_repeat('    ', $depth).']';

        return implode("\n", $lines);
    }

    private function discovery(InstallationSelection|InstallationDiscovery $installation): InstallationDiscovery
    {
        return $installation instanceof InstallationDiscovery
            ? $installation
            : InstallationDiscovery::explicit($installation);
    }

    private function servicePort(InstallationService $service, InstallationDiscovery $discovery, ?string $variable = null): string
    {
        $variable ??= $service->primaryPortVariable();
        $definition = $service->ports[$variable];
        if ($discovery->selection->provider === 'compose') {
            return '${'.$variable.'}';
        }

        return (string) $discovery->port($definition['discovery'], $definition['container']);
    }

    private function renderPorts(string $value, InstallationService $service, InstallationDiscovery $discovery): string
    {
        return preg_replace_callback(
            '/\{\{port(?::([A-Z][A-Z0-9_]*))?\}\}/',
            fn (array $match): string => $this->servicePort($service, $discovery, is_string($match[1] ?? null) ? $match[1] : null),
            $value,
        ) ?? $value;
    }
}
