<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Installation;

use LogicException;

final readonly class InstallationComposeRenderer
{
    public function __construct(private InstallationServiceCatalog $catalog = new InstallationServiceCatalog) {}

    public function render(InstallationSelection $selection): string
    {
        if ($selection->provider !== 'compose') {
            throw new LogicException('A Compose file can only be rendered for the Compose provider.');
        }

        $blocks = [];
        $volumes = [];
        foreach ($selection->services() as $name) {
            $service = $this->catalog->get($name);
            $blocks[] = $this->service($service);
            if ($service->volume !== null) {
                $volumes[] = "  {$service->name}-data:";
            }
        }

        $yaml = "# Generated by Harbour. PHP and Node continue to run natively.\nservices:\n".implode("\n", $blocks);
        if ($volumes !== []) {
            $yaml .= "\nvolumes:\n".implode("\n", $volumes)."\n";
        }

        return $yaml;
    }

    private function service(InstallationService $service): string
    {
        $lines = ["  {$service->name}:", "    image: {$service->image}"];
        if ($service->command !== null) {
            $lines[] = "    command: {$service->command}";
        }
        $lines[] = '    ports:';
        foreach ($service->ports as $variable => $port) {
            $lines[] = '      - "127.0.0.1:${'.$variable.'}:'.$port['container'].'"';
        }
        if ($service->composeEnvironment !== []) {
            $lines[] = '    environment:';
            foreach ($service->composeEnvironment as $variable => $value) {
                $lines[] = '      '.$variable.': '.$this->scalar($value);
            }
        }
        if ($service->volume !== null) {
            $lines[] = '    volumes:';
            $lines[] = "      - {$service->name}-data:{$service->volume}";
        }
        foreach ($service->composeProperties as $property => $value) {
            $lines[] = "    {$property}: {$value}";
        }
        $lines[] = '    healthcheck:';
        $lines[] = '      test: '.$this->inlineList($service->healthcheck);
        $lines[] = '      retries: 10';
        $lines[] = '      timeout: 5s';

        return implode("\n", $lines)."\n";
    }

    private function scalar(string $value): string
    {
        return preg_match('/^[A-Za-z][A-Za-z0-9_.\/-]*$/', $value) === 1
            ? $value
            : (string) json_encode($value, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    }

    /** @param list<string> $values */
    private function inlineList(array $values): string
    {
        return '['.implode(', ', array_map(
            static fn (string $value): string => (string) json_encode($value, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
            $values,
        )).']';
    }
}
