<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Installation;

use JsonException;
use PickeringTech\Harbour\Exceptions\ErrorCode;
use PickeringTech\Harbour\Exceptions\HarbourException;
use PickeringTech\Harbour\Support\AtomicFile;
use PickeringTech\Harbour\Support\WorkspacePath;

final readonly class ProjectUninstaller
{
    /** @var array<string, string> */
    private const MANAGED_FILE_PREFIXES = [
        '.env.harbour' => '# Generated by Harbour.',
        'config/harbour.php' => "<?php\n\ndeclare(strict_types=1);\n\n// Generated by Harbour.",
        'docker-compose.harbour.yml' => '# Generated by Harbour. PHP and Node continue to run natively.',
    ];

    public function __construct(
        private string $workspacePath,
        private AtomicFile $files = new AtomicFile,
    ) {}

    public function uninstall(): UninstallationResult
    {
        $removed = [];
        $absent = [];
        $retained = [];

        foreach (self::MANAGED_FILE_PREFIXES as $path => $prefix) {
            $this->removeManagedFile($path, $prefix, $removed, $absent, $retained);
        }

        $this->removeGitignoreBlock($removed, $absent, $retained);
        $this->removeComposerScripts($removed, $retained);

        return new UninstallationResult($removed, $absent, $retained);
    }

    /**
     * @param  list<string>  $removed
     * @param  list<string>  $absent
     * @param  list<string>  $retained
     */
    private function removeManagedFile(string $relative, string $prefix, array &$removed, array &$absent, array &$retained): void
    {
        $path = $this->uncheckedTarget($relative);
        if (! file_exists($path) && ! is_link($path)) {
            $absent[] = $relative;

            return;
        }
        if (is_link($path) || ! is_file($path)) {
            $retained[] = $relative.' (unsafe path)';

            return;
        }
        WorkspacePath::assertSafe($this->workspacePath, $path);

        $contents = @file_get_contents($path);
        if ($contents === false) {
            $retained[] = $relative.' (unreadable)';

            return;
        }
        if (! str_starts_with(str_replace("\r\n", "\n", $contents), $prefix)) {
            $retained[] = $relative.' (not generated by Harbour)';

            return;
        }
        if (! unlink($path)) {
            throw new HarbourException(ErrorCode::UnsafeOperation, "Unable to remove Harbour-managed project file [{$relative}].");
        }
        $removed[] = $relative;
    }

    /**
     * @param  list<string>  $removed
     * @param  list<string>  $absent
     * @param  list<string>  $retained
     */
    private function removeGitignoreBlock(array &$removed, array &$absent, array &$retained): void
    {
        $relative = '.gitignore';
        $path = $this->uncheckedTarget($relative);
        if (! file_exists($path) && ! is_link($path)) {
            $absent[] = $relative;

            return;
        }
        if (is_link($path) || ! is_file($path)) {
            $retained[] = $relative.' (unsafe path)';

            return;
        }
        WorkspacePath::assertSafe($this->workspacePath, $path);

        $contents = @file_get_contents($path);
        if ($contents === false) {
            $retained[] = $relative.' (unreadable)';

            return;
        }

        $marker = "# Harbour workspace state\n";
        $normalized = str_replace("\r\n", "\n", $contents);
        $position = strrpos($normalized, $marker);
        if ($position === false) {
            $absent[] = $relative.' Harbour block';

            return;
        }

        $suffix = substr($normalized, $position + strlen($marker));
        $entries = array_values(array_filter(explode("\n", $suffix), static fn (string $line): bool => $line !== ''));
        $allowed = ['/.harbour.json', '/.harbour/'];
        $valid = $suffix !== ''
            && str_ends_with($suffix, "\n")
            && count($entries) === count(array_unique($entries))
            && array_diff($entries, $allowed) === [];
        $prefix = substr($normalized, 0, $position);
        if (! $valid || ($prefix !== '' && ! str_ends_with($prefix, "\n\n"))) {
            $retained[] = $relative.' (Harbour block was modified)';

            return;
        }

        $replacement = $prefix === '' ? '' : substr($prefix, 0, -1);
        if (str_contains($contents, "\r\n")) {
            $replacement = str_replace("\n", "\r\n", $replacement);
        }
        $this->files->write($path, $replacement, 0644);
        $removed[] = $relative.' Harbour block';
    }

    /**
     * @param  list<string>  $removed
     * @param  list<string>  $retained
     */
    private function removeComposerScripts(array &$removed, array &$retained): void
    {
        $relative = 'composer.json';
        $path = $this->uncheckedTarget($relative);
        if (is_link($path) || ! is_file($path)) {
            $retained[] = $relative.' (missing or unsafe path)';

            return;
        }
        WorkspacePath::assertSafe($this->workspacePath, $path);
        $contents = @file_get_contents($path);
        if ($contents === false) {
            $retained[] = $relative.' (unreadable)';

            return;
        }

        try {
            $manifest = json_decode($contents, true, flags: JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json contains invalid JSON.', [], $exception);
        }
        if (! is_array($manifest) || array_is_list($manifest)) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json must contain a JSON object.');
        }
        $scripts = $manifest['scripts'] ?? [];
        if (! is_array($scripts)) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json scripts must be a JSON object.');
        }
        $remainingScripts = [];
        foreach ($scripts as $name => $commands) {
            if (! is_string($name)) {
                throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json script names must be strings.');
            }
            $remainingScripts[$name] = $commands;
        }

        $removedNames = [];
        foreach (ProjectInstaller::COMPOSER_SCRIPTS as $name => $commands) {
            if (($remainingScripts[$name] ?? null) === $commands) {
                unset($remainingScripts[$name]);
                $removedNames[] = $name;
            } elseif (array_key_exists($name, $remainingScripts)) {
                $retained[] = "composer.json scripts.{$name} (project-defined)";
            }
        }
        if ($removedNames === []) {
            return;
        }

        try {
            $encoded = $this->replaceComposerScripts($contents, $remainingScripts);
        } catch (JsonException $exception) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'Unable to encode composer.json.', [], $exception);
        }
        $this->files->write($path, $encoded, 0644);
        foreach ($removedNames as $name) {
            $removed[] = "composer.json scripts.{$name}";
        }
    }

    /**
     * @param  array<string, mixed>  $scripts
     *
     * @throws JsonException
     */
    private function replaceComposerScripts(string $contents, array $scripts): string
    {
        $open = $this->objectPropertyOpen($contents, 'scripts');
        if ($open === null) {
            throw new JsonException('Unable to locate composer.json scripts object.');
        }
        $close = $this->matchingBrace($contents, $open);
        $body = substr($contents, $open + 1, $close - $open - 1);
        $newline = str_contains($contents, "\r\n") ? "\r\n" : "\n";

        if (str_contains($body, "\n")) {
            $lineStart = strrpos(substr($contents, 0, $close), "\n");
            $closingStart = ($lineStart === false ? -1 : $lineStart) + 1;
            $closingIndent = substr($contents, $closingStart, $close - $closingStart);
            preg_match('/(?:\r?\n)([ \t]+)"/', $body, $indentMatch);
            $memberIndent = is_string($indentMatch[1] ?? null) ? $indentMatch[1] : $closingIndent.'    ';
            $replacement = $newline;
            if ($scripts !== []) {
                $replacement .= $this->scriptMembers($scripts, $memberIndent, $newline).$newline;
            }
            $replacement .= $closingIndent;
        } else {
            $replacement = $this->scriptMembers($scripts, '', '');
        }

        return substr($contents, 0, $open + 1).$replacement.substr($contents, $close);
    }

    /**
     * @param  array<string, mixed>  $scripts
     *
     * @throws JsonException
     */
    private function scriptMembers(array $scripts, string $indent, string $newline): string
    {
        $members = [];
        foreach ($scripts as $name => $commands) {
            $members[] = $indent
                .json_encode($name, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)
                .($indent === '' ? ':' : ': ')
                .json_encode($commands, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        }

        return implode(','.$newline, $members);
    }

    /** @throws JsonException */
    private function objectPropertyOpen(string $contents, string $property): ?int
    {
        $depth = 0;
        $length = strlen($contents);
        for ($index = 0; $index < $length; $index++) {
            $character = $contents[$index];
            if ($character === '{') {
                $depth++;

                continue;
            }
            if ($character === '}') {
                $depth--;

                continue;
            }
            if ($character !== '"') {
                continue;
            }

            $start = $index;
            $escaped = false;
            for ($index++; $index < $length; $index++) {
                $character = $contents[$index];
                if ($escaped) {
                    $escaped = false;
                } elseif ($character === '\\') {
                    $escaped = true;
                } elseif ($character === '"') {
                    break;
                }
            }
            if ($depth !== 1 || json_decode(substr($contents, $start, $index - $start + 1), true, flags: JSON_THROW_ON_ERROR) !== $property) {
                continue;
            }
            $cursor = $index + 1;
            while ($cursor < $length && ctype_space($contents[$cursor])) {
                $cursor++;
            }
            if (($contents[$cursor] ?? null) !== ':') {
                continue;
            }
            for ($cursor++; $cursor < $length && ctype_space($contents[$cursor]); $cursor++) {
                // Find the start of the property value.
            }

            return ($contents[$cursor] ?? null) === '{' ? $cursor : null;
        }

        return null;
    }

    private function matchingBrace(string $contents, int $open): int
    {
        $depth = 0;
        $inString = false;
        $escaped = false;
        $length = strlen($contents);
        for ($index = $open; $index < $length; $index++) {
            $character = $contents[$index];
            if ($inString) {
                if ($escaped) {
                    $escaped = false;
                } elseif ($character === '\\') {
                    $escaped = true;
                } elseif ($character === '"') {
                    $inString = false;
                }

                continue;
            }
            if ($character === '"') {
                $inString = true;
            } elseif ($character === '{') {
                $depth++;
            } elseif ($character === '}' && --$depth === 0) {
                return $index;
            }
        }

        throw new JsonException('Unable to locate composer.json scripts object boundary.');
    }

    private function uncheckedTarget(string $relative): string
    {
        return rtrim($this->workspacePath, DIRECTORY_SEPARATOR).'/'.$relative;
    }
}
