<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Installation;

use JsonException;
use PickeringTech\Harbour\Exceptions\ErrorCode;
use PickeringTech\Harbour\Exceptions\HarbourException;
use PickeringTech\Harbour\Support\AtomicFile;
use PickeringTech\Harbour\Support\WorkspacePath;

final readonly class ProjectInstaller
{
    /** @var array<string, list<string>> */
    private const COMPOSER_SCRIPTS = [
        'workspace:setup' => ['@php artisan workspace:setup'],
        'workspace:dev' => ['@php artisan workspace:dev'],
        'workspace:status' => ['@php artisan workspace:status'],
        'workspace:teardown' => ['@php artisan workspace:teardown'],
    ];

    public function __construct(
        private string $workspacePath,
        private AtomicFile $files = new AtomicFile,
        private InstallationFileRenderer $renderer = new InstallationFileRenderer,
        private InstallationComposeRenderer $compose = new InstallationComposeRenderer,
    ) {}

    public function install(InstallationSelection|InstallationDiscovery $installation, bool $reconfigure = false): InstallationResult
    {
        $discovery = $installation instanceof InstallationSelection
            ? InstallationDiscovery::explicit($installation)
            : $installation;
        $created = [];
        $updated = [];
        $unchanged = [];
        $conflicts = [];

        $this->writeManaged('.env.harbour', $this->renderer->environment($discovery), $reconfigure, $created, $updated, $unchanged);
        $this->writeManaged('config/harbour.php', $this->renderer->configuration($discovery), $reconfigure, $created, $updated, $unchanged);
        if ($discovery->selection->provider === 'compose') {
            $this->writeManaged('docker-compose.harbour.yml', $this->compose->render($discovery->selection), $reconfigure, $created, $updated, $unchanged);
        }
        $this->updateGitignore($updated, $unchanged);
        $this->updateComposer($updated, $unchanged, $conflicts);

        $protected = ['.env.harbour', 'config/harbour.php', 'docker-compose.harbour.yml'];
        $reconfigurePaths = $reconfigure ? [] : array_values(array_intersect($unchanged, $protected));

        return new InstallationResult($created, $updated, $unchanged, $conflicts, $discovery->selection, $discovery->metadata(), $reconfigurePaths);
    }

    /**
     * @param  list<string>  $created
     * @param  list<string>  $updated
     * @param  list<string>  $unchanged
     */
    private function writeManaged(string $destination, string $contents, bool $reconfigure, array &$created, array &$updated, array &$unchanged): void
    {
        $target = $this->target($destination);
        $this->assertRegularOrMissing($target);

        if (is_file($target)) {
            $existing = file_get_contents($target);
            if ($existing === false) {
                throw new HarbourException(ErrorCode::UnsafeOperation, "Unable to read existing project file [{$destination}].");
            }
            if ($reconfigure && str_contains(substr($existing, 0, 160), 'Generated by Harbour')) {
                if ($existing === $contents) {
                    $unchanged[] = $destination;
                } else {
                    $this->files->write($target, $contents, 0644);
                    $updated[] = $destination;
                }

                return;
            }
            $unchanged[] = $destination;

            return;
        }

        $this->files->write($target, $contents, 0644);
        $created[] = $destination;
    }

    /**
     * @param  list<string>  $updated
     * @param  list<string>  $unchanged
     */
    private function updateGitignore(array &$updated, array &$unchanged): void
    {
        $path = $this->target('.gitignore');
        $this->assertRegularOrMissing($path);
        $contents = is_file($path) ? file_get_contents($path) : '';
        if ($contents === false) {
            throw new HarbourException(ErrorCode::UnsafeOperation, 'Unable to read the project .gitignore.');
        }

        $lines = preg_split('/\R/', $contents) ?: [];
        $missing = array_values(array_filter(
            ['/.harbour.json', '/.harbour/'],
            static fn (string $entry): bool => ! in_array($entry, $lines, true),
        ));

        if ($missing === []) {
            $unchanged[] = '.gitignore';

            return;
        }

        $suffix = ($contents !== '' && ! str_ends_with($contents, "\n") ? "\n" : '')
            .($contents === '' ? '' : "\n")
            ."# Harbour workspace state\n"
            .implode("\n", $missing)."\n";
        $this->files->write($path, $contents.$suffix, 0644);
        $updated[] = '.gitignore';
    }

    /**
     * @param  list<string>  $updated
     * @param  list<string>  $unchanged
     * @param  list<string>  $conflicts
     */
    private function updateComposer(array &$updated, array &$unchanged, array &$conflicts): void
    {
        $path = $this->target('composer.json');
        $this->assertRegularOrMissing($path);
        if (! is_file($path)) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'Harbour must be installed from a Laravel project containing composer.json.');
        }

        $contents = file_get_contents($path);
        if ($contents === false) {
            throw new HarbourException(ErrorCode::UnsafeOperation, 'Unable to read composer.json.');
        }

        try {
            $manifest = json_decode($contents, true, flags: JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json contains invalid JSON.', [], $exception);
        }

        if (! is_array($manifest) || array_is_list($manifest)) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json must contain a JSON object.');
        }

        $scripts = $manifest['scripts'] ?? [];
        if (! is_array($scripts)) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'composer.json scripts must be a JSON object.');
        }

        $changed = false;
        $missingScripts = [];
        foreach (self::COMPOSER_SCRIPTS as $name => $commands) {
            if (! array_key_exists($name, $scripts)) {
                $scripts[$name] = $commands;
                $missingScripts[$name] = $commands;
                $changed = true;

                continue;
            }

            if ($scripts[$name] !== $commands) {
                $conflicts[] = "composer.json scripts.{$name}";
            }
        }

        if (! $changed) {
            $unchanged[] = 'composer.json';

            return;
        }

        try {
            $encoded = $this->insertComposerScripts($contents, $missingScripts, array_key_exists('scripts', $manifest));
        } catch (JsonException $exception) {
            throw new HarbourException(ErrorCode::InvalidConfiguration, 'Unable to encode composer.json.', [], $exception);
        }
        $this->files->write($path, $encoded, 0644);
        $updated[] = 'composer.json';
    }

    /**
     * @param  array<string, list<string>>  $scripts
     *
     * @throws JsonException
     */
    private function insertComposerScripts(string $contents, array $scripts, bool $hasScripts): string
    {
        $newline = str_contains($contents, "\r\n") ? "\r\n" : "\n";

        if ($hasScripts) {
            $open = $this->objectPropertyOpen($contents, 'scripts');
            if ($open === null) {
                throw new JsonException('Unable to locate composer.json scripts object.');
            }
            $close = $this->matchingBrace($contents, $open);
            $lineStart = strrpos(substr($contents, 0, $close), "\n");
            $closingIndent = substr($contents, ($lineStart === false ? -1 : $lineStart) + 1, $close - (($lineStart === false ? -1 : $lineStart) + 1));
            $body = substr($contents, $open + 1, $close - $open - 1);

            if (str_contains($body, "\n")) {
                $memberIndent = $closingIndent.'    ';
                $members = $this->scriptMembers($scripts, $memberIndent, $newline);
                $replacement = rtrim($body);
                if (trim($replacement) !== '') {
                    $replacement .= ',';
                }
                $replacement .= $newline.$members.$newline.$closingIndent;
            } else {
                $members = $this->scriptMembers($scripts, '', '');
                $replacement = $body.(trim($body) === '' ? '' : ',').$members;
            }

            return substr($contents, 0, $open + 1).$replacement.substr($contents, $close);
        }

        $trimmedEnd = rtrim($contents);
        $close = strlen($trimmedEnd) - 1;
        if ($close < 0 || $trimmedEnd[$close] !== '}') {
            throw new JsonException('Unable to locate composer.json root object.');
        }
        $suffix = substr($contents, strlen($trimmedEnd));
        $body = substr($trimmedEnd, 1, $close - 1);

        if (str_contains($body, "\n")) {
            preg_match('/(?:^|\R)([ \t]+)"/', $body, $indentMatch);
            $propertyIndent = is_string($indentMatch[1] ?? null) ? $indentMatch[1] : '    ';
            $members = $this->scriptMembers($scripts, $propertyIndent.'    ', $newline);
            $property = $propertyIndent.'"scripts": {'.$newline.$members.$newline.$propertyIndent.'}';
            $replacement = rtrim($body);
            if (trim($replacement) !== '') {
                $replacement .= ',';
            }
            $replacement .= $newline.$property.$newline;

            return '{'.$replacement.'}'.$suffix;
        }

        $members = $this->scriptMembers($scripts, '', '');

        return '{'.$body.(trim($body) === '' ? '' : ',').'"scripts":{'.$members.'}}'.$suffix;
    }

    /** @throws JsonException */
    private function objectPropertyOpen(string $contents, string $property): ?int
    {
        $depth = 0;
        $length = strlen($contents);

        for ($index = 0; $index < $length; $index++) {
            $character = $contents[$index];
            if ($character === '{') {
                $depth++;

                continue;
            }
            if ($character === '}') {
                $depth--;

                continue;
            }
            if ($character !== '"') {
                continue;
            }

            $start = $index;
            $escaped = false;
            for ($index++; $index < $length; $index++) {
                $character = $contents[$index];
                if ($escaped) {
                    $escaped = false;
                } elseif ($character === '\\') {
                    $escaped = true;
                } elseif ($character === '"') {
                    break;
                }
            }

            if ($depth !== 1 || json_decode(substr($contents, $start, $index - $start + 1), true, flags: JSON_THROW_ON_ERROR) !== $property) {
                continue;
            }
            $cursor = $index + 1;
            while ($cursor < $length && ctype_space($contents[$cursor])) {
                $cursor++;
            }
            if (($contents[$cursor] ?? null) !== ':') {
                continue;
            }
            for ($cursor++; $cursor < $length && ctype_space($contents[$cursor]); $cursor++) {
                // Find the start of the property value.
            }

            return ($contents[$cursor] ?? null) === '{' ? $cursor : null;
        }

        return null;
    }

    /** @param array<string, list<string>> $scripts */
    private function scriptMembers(array $scripts, string $indent, string $newline): string
    {
        $members = [];
        foreach ($scripts as $name => $commands) {
            $members[] = $indent
                .json_encode($name, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)
                .($indent === '' ? ':' : ': ')
                .json_encode($commands, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        }

        return implode(','.$newline, $members);
    }

    private function matchingBrace(string $contents, int $open): int
    {
        $depth = 0;
        $inString = false;
        $escaped = false;
        $length = strlen($contents);

        for ($index = $open; $index < $length; $index++) {
            $character = $contents[$index];
            if ($inString) {
                if ($escaped) {
                    $escaped = false;
                } elseif ($character === '\\') {
                    $escaped = true;
                } elseif ($character === '"') {
                    $inString = false;
                }

                continue;
            }
            if ($character === '"') {
                $inString = true;
            } elseif ($character === '{') {
                $depth++;
            } elseif ($character === '}' && --$depth === 0) {
                return $index;
            }
        }

        throw new JsonException('Unable to locate composer.json scripts object boundary.');
    }

    private function target(string $relative): string
    {
        $path = rtrim($this->workspacePath, DIRECTORY_SEPARATOR).'/'.$relative;
        WorkspacePath::assertSafe($this->workspacePath, $path);

        return $path;
    }

    private function assertRegularOrMissing(string $path): void
    {
        if (is_link($path) || (file_exists($path) && ! is_file($path))) {
            throw new HarbourException(ErrorCode::UnsafeOperation, "Refusing to install through unsafe project path [{$path}].");
        }
    }
}
