<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Installation;

final readonly class UninstallationResult
{
    /**
     * @param  list<string>  $removed
     * @param  list<string>  $absent
     * @param  list<string>  $retained
     */
    public function __construct(
        public array $removed,
        public array $absent,
        public array $retained,
    ) {}

    public function withProjectFile(string $path, string $change): self
    {
        $removed = $this->removed;
        $absent = $this->absent;
        $retained = $this->retained;
        match ($change) {
            'removed' => $removed[] = $path,
            'retained' => $retained[] = $path.' (not generated by Harbour or modified)',
            default => $absent[] = $path.' Harbour block',
        };

        return new self($removed, $absent, $retained);
    }

    /** @return array{removed: list<string>, absent: list<string>, retained: list<string>} */
    public function toArray(): array
    {
        return [
            'removed' => $this->removed,
            'absent' => $this->absent,
            'retained' => $this->retained,
        ];
    }
}
