<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Console;

use function Laravel\Prompts\confirm;
use function Laravel\Prompts\intro;
use function Laravel\Prompts\multiselect;
use function Laravel\Prompts\select;

use PickeringTech\Harbour\Contracts\InstallationDependencyInstaller;
use PickeringTech\Harbour\Contracts\InstallationPreflight;
use PickeringTech\Harbour\Contracts\InstalledApplicationLauncher;
use PickeringTech\Harbour\Contracts\InstalledWorkspaceStarter;
use PickeringTech\Harbour\Exceptions\ErrorCode;
use PickeringTech\Harbour\Exceptions\HarbourException;
use PickeringTech\Harbour\Installation\ArtisanWorkspaceStarter;
use PickeringTech\Harbour\Installation\InstallationDiscovery;
use PickeringTech\Harbour\Installation\InstallationPlan;
use PickeringTech\Harbour\Installation\InstallationRequirement;
use PickeringTech\Harbour\Installation\InstallationRuntimeResolver;
use PickeringTech\Harbour\Installation\InstallationSelection;
use PickeringTech\Harbour\Installation\InstallationServiceCatalog;
use PickeringTech\Harbour\Installation\ProjectConfigurationDetector;
use PickeringTech\Harbour\Installation\ProjectInstaller;

final class InstallCommand extends WorkspaceCommand
{
    protected $signature = 'workspace:install
        {--d|database= : Database: none, sqlite, mysql, mariadb, pgsql, mongodb}
        {--c|cache= : Cache: none, file, database, redis, valkey, memcached}
        {--m|mail= : Mail: none, log, mailpit}
        {--with= : Sail-compatible comma-separated services, or none}
        {--detect : Accept the configuration inferred from Sail, Herd, and Laravel files}
        {--provider= : Service provider: shared or compose}
        {--redis-client= : Redis client: auto, phpredis, or predis}
        {--compose : Generate a workspace-managed Docker Compose stack}
        {--reconfigure : Replace only files previously generated by Harbour}
        {--install-dependencies : Install missing Composer integrations without prompting}
        {--start : Set up this workspace and start managed services after installation}
        {--launch : Set up and launch Laravel and Vite without prompting}
        {--json : Emit stable JSON; use --detect or supply selections as options}';

    protected $description = 'Prepare this Laravel project for Harbour without overwriting existing choices';

    public function handle(
        ProjectInstaller $installer,
        ProjectConfigurationDetector $detector,
        InstalledWorkspaceStarter $starter,
        InstallationServiceCatalog $services,
        InstallationPreflight $preflight,
        InstallationDependencyInstaller $dependencies,
        InstallationRuntimeResolver $runtime,
        InstalledApplicationLauncher $application,
    ): int {
        $json = (bool) $this->option('json');

        return $this->executeSafely($json, function () use ($installer, $detector, $starter, $services, $preflight, $dependencies, $runtime, $application, $json): int {
            if ($json && (bool) $this->option('launch')) {
                throw new HarbourException(ErrorCode::InvalidInstallSelection, '--launch cannot be combined with --json because launching is an attached development session.');
            }
            $plan = $this->installation($json, $detector, $services);
            $plan = $plan->withDiscovery($runtime->resolve($plan->discovery));
            $discovery = $plan->discovery;
            $selection = $discovery->selection;
            $dependenciesApproved = $this->installDependencies($selection, $preflight, $dependencies, $json, $plan->start);
            if ($json) {
                $this->assertReady($preflight, $selection, $plan->start, $dependenciesApproved);
            } else {
                $this->components->task('Checking selected stack requirements', fn () => $this->assertReady($preflight, $selection, $plan->start, $dependenciesApproved));
            }
            $result = $installer->install($discovery, (bool) $this->option('reconfigure'));
            $startOutput = '';

            if ($plan->start) {
                if ($json) {
                    $startOutput = $starter->start();
                } else {
                    $this->components->info('Setting up this workspace; managed service output follows.');
                    $startOutput = $starter->start(function (string $type, string $buffer): void {
                        $this->output->write($buffer);
                    });
                }
            }

            if ($json) {
                $payload = [
                    'version' => 1,
                    'ok' => true,
                    'installation' => [...$result->toArray(), 'started' => $plan->start],
                ];
                if ($startOutput !== '') {
                    $payload['workspace'] = $this->startedWorkspace($startOutput);
                }
                $this->line((string) json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));

                return self::SUCCESS;
            }

            $this->components->info('Harbour project files are ready.');
            $this->components->twoColumnDetail('Database', $selection->database);
            $this->components->twoColumnDetail('Cache', $selection->cache);
            $this->components->twoColumnDetail('Mail', $selection->mail);
            $this->components->twoColumnDetail('Provider', $selection->provider === 'compose' ? 'Docker Compose' : 'shared infrastructure');
            $this->components->twoColumnDetail('Services', $selection->services() === [] ? 'none' : implode(', ', $selection->services()));
            if ($discovery->sources !== []) {
                $this->components->twoColumnDetail('Detected from', implode(', ', $discovery->sources));
            }
            $this->newLine();
            foreach ($result->created as $path) {
                $this->components->task("Created {$path}");
            }
            foreach ($result->updated as $path) {
                $this->components->task("Updated {$path}");
            }
            foreach ($result->unchanged as $path) {
                $this->components->twoColumnDetail($path, '<fg=gray>already configured</>');
            }
            foreach ($result->reconfigure as $path) {
                $this->components->warn("To change the installation selection, delete {$path} and rerun workspace:install; Harbour will never overwrite it.");
            }
            foreach ($result->conflicts as $path) {
                $this->components->warn("Kept existing {$path}; Harbour never replaces a project-defined script.");
            }
            $this->newLine();
            if ($plan->start) {
                if ($startOutput !== '') {
                    $this->displayWorkspace($this->startedWorkspace($startOutput));
                }
                $this->line('The project policy and isolated environment are ready.');
            } else {
                $this->line('Review <comment>.env.harbour</comment>, commit the project files, then run <comment>composer workspace:setup</comment>.');
            }

            if ($plan->start && $this->shouldLaunch()) {
                $this->newLine();
                $this->components->info('Launching Laravel and Vite; press Ctrl+C when you are finished.');
                $application->launch(output: fn (string $type, string $buffer) => $this->output->write($buffer));
            }

            return self::SUCCESS;
        });
    }

    private function installation(bool $json, ProjectConfigurationDetector $detector, InstallationServiceCatalog $services): InstallationPlan
    {
        $database = $this->stringOption('database');
        $cache = $this->stringOption('cache');
        $mail = $this->stringOption('mail');
        $with = $this->stringOption('with');
        $provider = $this->providerOption();
        $redisClient = $this->stringOption('redis-client');
        $detect = (bool) $this->option('detect');
        $start = (bool) $this->option('start') || (bool) $this->option('launch');
        $explicit = $database !== null || $cache !== null || $mail !== null || $with !== null || $redisClient !== null;

        if ($detect) {
            $discovery = $detector->discover();
            $selection = InstallationSelection::fromOptions(
                $database ?? $discovery->selection->database,
                $cache ?? $discovery->selection->cache,
                $mail ?? $discovery->selection->mail,
                $with ?? $this->serviceList($discovery->selection->additionalServices),
                $provider ?? $discovery->selection->provider,
                $redisClient ?? $discovery->selection->redisClient,
            );

            return new InstallationPlan($discovery->withSelection($selection), $start);
        }

        if ($explicit) {
            return new InstallationPlan(
                InstallationDiscovery::explicit(InstallationSelection::fromOptions($database, $cache, $mail, $with, $provider, $redisClient)),
                $start,
            );
        }

        if ($json || ! $this->input->isInteractive()) {
            throw new HarbourException(
                ErrorCode::InstallSelectionRequired,
                'Use --detect or choose services explicitly with --database, --cache, --mail, and/or --with=none in non-interactive mode.',
            );
        }

        intro('Configure Harbour');
        $mode = select(
            label: 'How would you like to configure this project?',
            options: [
                'detect' => 'Auto-detect from this project',
                'manual' => 'Choose components manually',
            ],
            default: 'detect',
            hint: 'Use the arrow keys and press Enter.',
        );

        if ($mode === 'detect') {
            $discovery = $detector->discover();
            $this->showProposal($discovery, $services);
            $question = $discovery->detected
                ? 'Use these detected settings?'
                : 'Use this zero-dependency setup?';

            if (confirm($question, true)) {
                return new InstallationPlan($discovery, $this->confirmStart($discovery->selection, $start));
            }
        } elseif ($mode === 'manual') {
            $discovery = $detector->discover();
        } else {
            throw new HarbourException(ErrorCode::InvalidInstallSelection, 'Choose auto-detection or manual component selection.');
        }

        $databaseChoice = select(
            label: 'Which database connection should Laravel use?',
            options: [
                'none' => 'None',
                'sqlite' => 'SQLite',
                ...$services->optionsFor('database'),
            ],
            default: $discovery->selection->database,
            scroll: count(InstallationSelection::databases()),
            hint: 'SQL databases are isolated; MongoDB is connection-only.',
        );
        $cacheChoice = select(
            label: 'Which cache and shared-state store should Laravel use?',
            options: [
                'none' => 'None / array',
                'file' => 'File',
                'database' => 'Database',
                ...$services->optionsFor('cache'),
            ],
            default: $discovery->selection->cache,
            scroll: count(InstallationSelection::caches()),
        );
        $mailChoice = select(
            label: 'Which mail transport should Laravel use locally?',
            options: [
                'none' => 'None / array',
                'log' => 'Log',
                ...$services->optionsFor('mail'),
            ],
            default: $discovery->selection->mail,
            scroll: count(InstallationSelection::mailers()),
        );
        $additionalChoice = multiselect(
            label: 'Which additional components should Harbour configure?',
            options: $services->optionsFor('additional'),
            default: $discovery->selection->additionalServices,
            scroll: count(InstallationSelection::additionalServices()),
            hint: 'Use Space to select multiple components, then press Enter.',
        );

        $additional = [];
        foreach ($additionalChoice as $service) {
            $additional[] = $this->choiceString($service, 'additional service');
        }

        $selection = InstallationSelection::fromOptions(
            $this->choiceString($databaseChoice, 'database'),
            $this->choiceString($cacheChoice, 'cache'),
            $this->choiceString($mailChoice, 'mail'),
            $additional === [] ? 'none' : implode(',', $additional),
            null,
            $redisClient,
        );

        if ($provider !== null) {
            $selection = $selection->withProvider($provider);
        } elseif ($selection->services() !== []) {
            $useCompose = confirm(
                label: 'Use Docker Compose for these service-backed components?',
                default: false,
                hint: 'No keeps using existing shared infrastructure.',
            );
            if ($useCompose) {
                $selection = $selection->withProvider('compose');
            }
        }

        return new InstallationPlan($discovery->withManualSelection($selection), $this->confirmStart($selection, $start));
    }

    private function shouldLaunch(): bool
    {
        if ((bool) $this->option('launch')) {
            return true;
        }
        if (! $this->input->isInteractive()) {
            return false;
        }

        return confirm(
            label: 'Launch Laravel and Vite now?',
            default: true,
            hint: 'The processes stay attached to this terminal and stop cleanly with Ctrl+C.',
        );
    }

    private function installDependencies(
        InstallationSelection $selection,
        InstallationPreflight $preflight,
        InstallationDependencyInstaller $dependencies,
        bool $json,
        bool $start,
    ): bool {
        $requirements = array_values(array_filter(
            $preflight->requirements($selection),
            static fn (InstallationRequirement $requirement): bool => $requirement->composerPackage() !== null,
        ));
        if ($requirements === []) {
            return false;
        }

        $install = (bool) $this->option('install-dependencies');
        if (! $install && ! $json && $this->input->isInteractive()) {
            $packages = array_map(
                static fn (InstallationRequirement $requirement): string => (string) $requirement->composerPackage(),
                $requirements,
            );
            $install = confirm(
                label: 'Install the selected Laravel integration packages now?',
                default: true,
                hint: 'Harbour will run Composer once for: '.implode(', ', $packages).'.',
            );
        }
        if (! $install) {
            return false;
        }

        $output = null;
        if (! $json) {
            $this->components->info('Installing the selected Laravel integrations with Composer.');
            $output = fn (string $type, string $buffer) => $this->output->write($buffer);
        }
        try {
            $dependencies->install($requirements, $output);
        } catch (HarbourException $exception) {
            if ($exception->errorCode !== ErrorCode::ProcessFailed) {
                throw $exception;
            }

            throw new HarbourException(
                $exception->errorCode,
                $exception->getMessage(),
                [...$exception->context, 'retry_command' => $this->retryCommand($selection, $start, true)],
                $exception,
            );
        }

        return true;
    }

    private function assertReady(
        InstallationPreflight $preflight,
        InstallationSelection $selection,
        bool $start,
        bool $dependenciesApproved,
    ): void {
        try {
            $preflight->assertReady($selection);
        } catch (HarbourException $exception) {
            if ($exception->errorCode !== ErrorCode::InstallRequirementsMissing || ! $start) {
                throw $exception;
            }

            $context = $exception->context;
            $context['retry_command'] = $this->retryCommand($selection, $start, $dependenciesApproved);

            throw new HarbourException($exception->errorCode, $exception->getMessage(), $context, $exception);
        }
    }

    private function retryCommand(InstallationSelection $selection, bool $start, bool $installDependencies): string
    {
        $services = $selection->additionalServices === [] ? 'none' : implode(',', $selection->additionalServices);
        $command = 'php artisan workspace:install'
            .' --database='.$selection->database
            .' --cache='.$selection->cache
            .' --mail='.$selection->mail
            .' --with='.$services
            .' --provider='.$selection->provider
            .' --redis-client='.$selection->redisClient;

        if ($installDependencies) {
            $command .= ' --install-dependencies';
        }
        if ($start) {
            $command .= ' --start';
        }

        return $command;
    }

    private function confirmStart(InstallationSelection $selection, bool $start): bool
    {
        if ($start) {
            return true;
        }

        $startLabel = $selection->provider === 'compose'
            ? 'Start these Docker Compose components and set up this workspace now?'
            : 'Set up this workspace now?';

        return confirm(
            label: $startLabel,
            default: $selection->provider === 'compose',
            hint: $selection->provider === 'compose'
                ? 'Harbour will wait until the services are ready.'
                : 'You can always run composer workspace:setup later.',
        );
    }

    /** @return array<string, mixed> */
    private function startedWorkspace(string $output): array
    {
        return ArtisanWorkspaceStarter::workspaceFromOutput($output);
    }

    private function showProposal(InstallationDiscovery $discovery, InstallationServiceCatalog $services): void
    {
        $this->newLine();
        $this->components->info($discovery->detected ? 'Harbour detected this project configuration.' : 'No external infrastructure configuration was detected.');
        $this->components->twoColumnDetail('Database', $discovery->selection->database);
        $this->components->twoColumnDetail('Cache', $discovery->selection->cache);
        $this->components->twoColumnDetail('Mail', $discovery->selection->mail);
        $this->components->twoColumnDetail('Additional services', $discovery->selection->additionalServices === [] ? 'none' : implode(', ', $discovery->selection->additionalServices));
        if ($discovery->sources !== []) {
            $this->components->twoColumnDetail('Sources', implode(', ', $discovery->sources));
        }
        if ($discovery->selection->provider === 'shared' && $discovery->localServices !== []) {
            $prerequisites = [];
            foreach ($discovery->localServices as $service) {
                $prerequisites[] = $service.' on 127.0.0.1:'.$discovery->port($service, $services->get($service)->defaultPort());
            }
            $this->components->warn('Shared infrastructure must already be listening: '.implode(', ', $prerequisites).'. Detection does not switch these services to Compose.');
        }
        $this->newLine();
    }

    /** @param list<string> $services */
    private function serviceList(array $services): string
    {
        return $services === [] ? 'none' : implode(',', $services);
    }

    private function stringOption(string $name): ?string
    {
        $value = $this->option($name);

        if ($value === null) {
            return null;
        }
        if (! is_string($value)) {
            throw new HarbourException(ErrorCode::InvalidInstallSelection, "The --{$name} option must be a string.");
        }

        return $value;
    }

    private function providerOption(): ?string
    {
        $provider = $this->stringOption('provider');
        if ((bool) $this->option('compose')) {
            if ($provider !== null && strtolower(trim($provider)) !== 'compose') {
                throw new HarbourException(ErrorCode::InvalidInstallSelection, 'The --compose flag conflicts with --provider='.$provider.'.');
            }

            return 'compose';
        }

        if ($provider === null) {
            return null;
        }

        $normalized = strtolower(trim($provider));
        if (! in_array($normalized, InstallationSelection::PROVIDERS, true)) {
            throw new HarbourException(
                ErrorCode::InvalidInstallSelection,
                'Unsupported infrastructure provider ['.$provider.']. Choose one of: '.implode(', ', InstallationSelection::PROVIDERS).'.',
            );
        }

        return $normalized;
    }

    private function choiceString(mixed $choice, string $group): string
    {
        if (! is_string($choice)) {
            throw new HarbourException(ErrorCode::InvalidInstallSelection, "The interactive {$group} choice must be a string.");
        }

        return strtolower($choice);
    }
}
