<?php

declare(strict_types=1);

namespace PickeringTech\Harbour\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use PickeringTech\Harbour\Exceptions\HarbourException;
use PickeringTech\Harbour\Installation\InstallationSelection;
use PickeringTech\Harbour\Installation\ProjectInstaller;
use PickeringTech\Harbour\Installation\ProjectUninstaller;

final class ProjectUninstallerTest extends TestCase
{
    private string $workspace;

    protected function setUp(): void
    {
        $this->workspace = sys_get_temp_dir().'/harbour-uninstaller-'.bin2hex(random_bytes(6));
        mkdir($this->workspace, 0700, true);
        file_put_contents($this->workspace.'/composer.json', "{\n    \"name\": \"acme/app\",\n    \"scripts\": {\n        \"test\": \"phpunit\"\n    }\n}\n");
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->workspace);
    }

    public function test_it_removes_only_harbour_managed_project_policy(): void
    {
        file_put_contents($this->workspace.'/.gitignore', "/vendor\n");
        $installer = new ProjectInstaller($this->workspace);
        $installer->install(InstallationSelection::fromOptions('pgsql', 'redis', 'mailpit', 'meilisearch', 'compose'));

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertEqualsCanonicalizing([
            '.env.harbour',
            'config/harbour.php',
            'docker-compose.harbour.yml',
            '.gitignore Harbour block',
            'composer.json scripts.workspace:setup',
            'composer.json scripts.workspace:dev',
            'composer.json scripts.workspace:status',
            'composer.json scripts.workspace:teardown',
            'composer.json scripts.workspace:uninstall',
        ], $result->removed);
        self::assertSame([], $result->retained);
        self::assertFileDoesNotExist($this->workspace.'/.env.harbour');
        self::assertFileDoesNotExist($this->workspace.'/config/harbour.php');
        self::assertFileDoesNotExist($this->workspace.'/docker-compose.harbour.yml');
        self::assertSame("/vendor\n", file_get_contents($this->workspace.'/.gitignore'));
        self::assertSame(['test' => 'phpunit'], $this->composerScripts());
    }

    public function test_it_retains_unmarked_project_content_and_modified_ownership_blocks(): void
    {
        mkdir($this->workspace.'/config');
        file_put_contents($this->workspace.'/.env.harbour', "CUSTOM=true\n");
        file_put_contents($this->workspace.'/config/harbour.php', "<?php return ['custom' => true];\n");
        file_put_contents($this->workspace.'/docker-compose.harbour.yml', "services:\n  custom: {}\n");
        file_put_contents($this->workspace.'/.gitignore', "# Harbour workspace state\n/.harbour.json\n/custom\n");
        file_put_contents($this->workspace.'/composer.json', json_encode([
            'name' => 'acme/app',
            'scripts' => [
                'workspace:setup' => ['custom setup'],
                'workspace:status' => ['@php artisan workspace:status'],
            ],
        ], JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR)."\n");

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertSame(['composer.json scripts.workspace:status'], $result->removed);
        self::assertEqualsCanonicalizing([
            '.env.harbour (not generated by Harbour)',
            'config/harbour.php (not generated by Harbour)',
            'docker-compose.harbour.yml (not generated by Harbour)',
            '.gitignore (Harbour block was modified)',
            'composer.json scripts.workspace:setup (project-defined)',
        ], $result->retained);
        self::assertFileExists($this->workspace.'/.env.harbour');
        self::assertStringContainsString('/custom', (string) file_get_contents($this->workspace.'/.gitignore'));
        self::assertSame(['workspace:setup' => ['custom setup']], $this->composerScripts());
    }

    public function test_it_preserves_preexisting_gitignore_entries_that_harbour_did_not_add(): void
    {
        file_put_contents($this->workspace.'/.gitignore', "/.harbour.json\n");
        (new ProjectInstaller($this->workspace))->install(new InstallationSelection('sqlite', 'file', 'log'));

        (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertSame("/.harbour.json\n", file_get_contents($this->workspace.'/.gitignore'));
    }

    public function test_it_removes_aliases_without_reformatting_unrelated_composer_content(): void
    {
        $manifest = "{\r\n\t\"name\": \"acme/app\",\r\n\t\"scripts\": {\r\n\t\t\"test\": \"say {ok}\",\r\n\t\t\"workspace:setup\": [\"@php artisan workspace:setup\"]\r\n\t},\r\n\t\"extra\": {\"nested\":{\"keep\":true}}\r\n}\r\n";
        file_put_contents($this->workspace.'/composer.json', $manifest);

        (new ProjectUninstaller($this->workspace))->uninstall();

        $updated = (string) file_get_contents($this->workspace.'/composer.json');
        self::assertStringContainsString("\t\"extra\": {\"nested\":{\"keep\":true}}", $updated);
        self::assertStringContainsString("\t\t\"test\": \"say {ok}\"", $updated);
        self::assertStringNotContainsString('workspace:setup', $updated);
        self::assertSame(0, preg_match('/(?<!\r)\n/', $updated));
    }

    public function test_it_is_idempotent_and_refuses_to_follow_symlinks(): void
    {
        $outside = $this->workspace.'-outside';
        file_put_contents($outside, "# Generated by Harbour.\nvaluable=true\n");
        symlink($outside, $this->workspace.'/.env.harbour');

        $first = (new ProjectUninstaller($this->workspace))->uninstall();
        $second = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertContains('.env.harbour (unsafe path)', $first->retained);
        self::assertContains('.env.harbour (unsafe path)', $second->retained);
        self::assertSame("# Generated by Harbour.\nvaluable=true\n", file_get_contents($outside));
        unlink($outside);
    }

    public function test_it_removes_a_crlf_gitignore_block_and_compact_aliases(): void
    {
        file_put_contents($this->workspace.'/.gitignore', "/vendor\r\n\r\n# Harbour workspace state\r\n/.harbour.json\r\n/.harbour/\r\n");
        file_put_contents($this->workspace.'/composer.json', '{"scripts":{"test":"phpunit","workspace:setup":["@php artisan workspace:setup"]},"extra":{"keep":true}}');

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertContains('.gitignore Harbour block', $result->removed);
        self::assertSame("/vendor\r\n", file_get_contents($this->workspace.'/.gitignore'));
        self::assertSame('{"scripts":{"test":"phpunit"},"extra":{"keep":true}}', file_get_contents($this->workspace.'/composer.json'));
    }

    public function test_it_can_remove_the_only_ignore_block_and_the_only_compact_script(): void
    {
        file_put_contents($this->workspace.'/.gitignore', "# Harbour workspace state\n/.harbour.json\n/.harbour/\n");
        file_put_contents($this->workspace.'/composer.json', '{"scripts":{"workspace:setup":["@php artisan workspace:setup"]}}');

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertContains('.gitignore Harbour block', $result->removed);
        self::assertSame('', file_get_contents($this->workspace.'/.gitignore'));
        self::assertSame('{"scripts":{}}', file_get_contents($this->workspace.'/composer.json'));
    }

    public function test_it_reports_absent_policy_without_rewriting_project_content(): void
    {
        $composer = (string) file_get_contents($this->workspace.'/composer.json');

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertEqualsCanonicalizing([
            '.env.harbour',
            'config/harbour.php',
            'docker-compose.harbour.yml',
            '.gitignore',
        ], $result->absent);
        self::assertSame([], $result->removed);
        self::assertSame($composer, file_get_contents($this->workspace.'/composer.json'));
    }

    public function test_it_reports_a_gitignore_without_a_harbour_block_as_absent(): void
    {
        file_put_contents($this->workspace.'/.gitignore', "/vendor\n");

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertContains('.gitignore Harbour block', $result->absent);
        self::assertSame("/vendor\n", file_get_contents($this->workspace.'/.gitignore'));
    }

    public function test_it_retains_unreadable_project_paths(): void
    {
        file_put_contents($this->workspace.'/.env.harbour', "# Generated by Harbour.\n");
        file_put_contents($this->workspace.'/.gitignore', "# Harbour workspace state\n/.harbour.json\n/.harbour/\n");
        chmod($this->workspace.'/.env.harbour', 0000);
        chmod($this->workspace.'/.gitignore', 0000);
        chmod($this->workspace.'/composer.json', 0000);

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertContains('.env.harbour (unreadable)', $result->retained);
        self::assertContains('.gitignore (unreadable)', $result->retained);
        self::assertContains('composer.json (unreadable)', $result->retained);
    }

    public function test_it_rejects_ambiguous_duplicate_composer_script_properties(): void
    {
        file_put_contents(
            $this->workspace.'/composer.json',
            '{"scripts":"ambiguous","scripts":{"workspace:setup":["@php artisan workspace:setup"]}}',
        );

        $this->expectException(HarbourException::class);
        $this->expectExceptionMessage('Unable to encode composer.json');
        (new ProjectUninstaller($this->workspace))->uninstall();
    }

    public function test_composer_scanning_rejects_an_earlier_non_object_scripts_property(): void
    {
        file_put_contents(
            $this->workspace.'/composer.json',
            '{"name":"scripts","extra":{"scripts":{}},"scripts":[],"scripts":{"workspace:setup":["@php artisan workspace:setup"]}}',
        );

        $this->expectException(HarbourException::class);
        $this->expectExceptionMessage('Unable to encode composer.json');
        (new ProjectUninstaller($this->workspace))->uninstall();
    }

    public function test_an_owned_file_that_cannot_be_removed_fails_closed(): void
    {
        file_put_contents($this->workspace.'/.env.harbour', "# Generated by Harbour.\n");
        chmod($this->workspace, 0500);

        try {
            (new ProjectUninstaller($this->workspace))->uninstall();
            self::fail('An owned file that cannot be unlinked must fail closed.');
        } catch (HarbourException $exception) {
            self::assertStringContainsString('Unable to remove', $exception->getMessage());
        } finally {
            chmod($this->workspace, 0700);
        }
    }

    /** @param non-empty-string $message */
    #[DataProvider('invalidComposerManifests')]
    public function test_it_rejects_malformed_composer_manifests(string $manifest, string $message): void
    {
        file_put_contents($this->workspace.'/composer.json', $manifest);

        $this->expectException(HarbourException::class);
        $this->expectExceptionMessage($message);
        (new ProjectUninstaller($this->workspace))->uninstall();
    }

    /** @return iterable<string, array{string, non-empty-string}> */
    public static function invalidComposerManifests(): iterable
    {
        yield 'invalid JSON' => ['{invalid', 'invalid JSON'];
        yield 'non-object root' => ['[]', 'JSON object'];
        yield 'non-object scripts' => ['{"scripts":"invalid"}', 'scripts must be a JSON object'];
        yield 'numeric script name' => ['{"scripts":{"0":"invalid"}}', 'script names must be strings'];
    }

    public function test_it_retains_unsafe_gitignore_and_composer_paths(): void
    {
        unlink($this->workspace.'/composer.json');
        $outsideGitignore = $this->workspace.'-gitignore';
        $outsideComposer = $this->workspace.'-composer';
        file_put_contents($outsideGitignore, "# Harbour workspace state\n/.harbour.json\n");
        file_put_contents($outsideComposer, '{"scripts":{}}');
        symlink($outsideGitignore, $this->workspace.'/.gitignore');
        symlink($outsideComposer, $this->workspace.'/composer.json');

        $result = (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertContains('.gitignore (unsafe path)', $result->retained);
        self::assertContains('composer.json (missing or unsafe path)', $result->retained);
        self::assertSame("# Harbour workspace state\n/.harbour.json\n", file_get_contents($outsideGitignore));
        self::assertSame('{"scripts":{}}', file_get_contents($outsideComposer));
        unlink($outsideGitignore);
        unlink($outsideComposer);
    }

    public function test_composer_scanner_handles_whitespace_and_escaped_quotes_inside_scripts(): void
    {
        file_put_contents($this->workspace.'/composer.json', <<<'JSON'
        {
          "scripts"
          : {
            "note": "say \"hello\"",
            "workspace:setup": ["@php artisan workspace:setup"],
            "workspace:teardown": ["@php artisan workspace:teardown"]
          }
        }
        JSON);

        (new ProjectUninstaller($this->workspace))->uninstall();

        self::assertSame(['note' => 'say "hello"'], $this->composerScripts());
    }

    /** @return array<string, mixed> */
    private function composerScripts(): array
    {
        $manifest = json_decode((string) file_get_contents($this->workspace.'/composer.json'), true, flags: JSON_THROW_ON_ERROR);
        self::assertIsArray($manifest);
        $scripts = $manifest['scripts'] ?? null;
        self::assertIsArray($scripts);

        $result = [];
        foreach ($scripts as $name => $commands) {
            self::assertIsString($name);
            $result[$name] = $commands;
        }

        return $result;
    }

    private function removeDirectory(string $path): void
    {
        if (! is_dir($path)) {
            return;
        }
        foreach (scandir($path) ?: [] as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            $child = $path.'/'.$entry;
            is_dir($child) && ! is_link($child) ? $this->removeDirectory($child) : @unlink($child);
        }
        @rmdir($path);
    }
}
